services:
  postgres:
    container_name: postgres_cb_restaurant_ordering
    image: postgres:alpine3.19
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

#  app:
#    image: macchiato23/crispy-broccoli-restaurant-ordering:0.0.1-SNAPSHOT
#    container_name: app_cb_restaurant_ordering
#    ports:
#      - "8181:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - postgres
#    depends_on:
#      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: