server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:restaurant-ordering}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:postgres}:${DATABASE_PORT:5432}/${DATABASE_NAME:restaurant_ordering}
    password: ${DATABASE_PASSWORD:password}
    username: ${DATABASE_USER:default}
    driver-class-name: org.postgresql.Driver


springdoc:
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-ui.html}
  api-docs:
    path: ${API_DOCS_PATH:/v3/api-docs}
logging:
  level:
    root: warn